### PR TITLE
Added support for cordova 3, added png mimetype

### PR DESCRIPTION
**Pull request by antonioJASR**
Hello, your plugin is nice. But, it doesn't have support for cordova 3, so... I added it.

Greetings.

### CODE REVIEW

**Comment by Anj1ana** [comment]
Is it supporting cordova 3.4.0??

**Comment by antonioJASR** [comment]
@Anj1ana, it should be work on cordova 3.4, but if you detect some issue please let me know.

**Comment by markeeftb** [comment]
Good work guys. Just needed the new version and voila - it's there! Thanks!

**Comment by Anj1ana** [comment]
Hey  @antonioJASR ,
My PDF file is not opening and I'm not even getting any error. This is my Index.html. Please Help asap.

```
<script type="text/javascript" charset="utf-8" src="cordova.js"></script>
<script type="text/javascript" charset="utf-8">

// Wait for device API libraries to load

document.addEventListener("deviceready", onDeviceReady, false);

// device APIs are available

function onDeviceReady() 
{
     var ref = window.plugins.fileOpener.open("file:///sdcard/Download/AISB08.pdf");
}
</script>
```

**Comment by akhilesh0707** [comment]
Hey guys i'm not able to find the FileOpener plugin in build.phonegap.com, can you please help me out how to find the FileOpener plugin

**Comment by antonioJASR** [comment]
Have you tried this
http://stackoverflow.com/questions/19873812/phonegap-build-plugins-not-working
?

On Mon, Mar 30, 2015 at 6:37 AM, Akhilesh Patil notifications@github.com
wrote:

> Hey guys i'm not able to find the FileOpener plugin in build.phonegap.com,
> can you please help me out how to find the plugin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markeeftb/FileOpener/pull/9#issuecomment-87662223.

## 

_KISS - Keep It Sort and Simple_

**Pull request merged**
